# サイトの基本設定
title: info for Sora # サイトのタイトルを"info for Sora"に変更しました
# email: your-email@example.com # あなたのメールアドレス（オプション）- コメントアウトしました
description: > # サイトの簡単な説明。検索エンジンに表示されることがあります。
  Lunatisプロジェクトに関するAI（ソラ）のための情報共有プラットフォームです。
  プロジェクトの進捗、システム詳細、スクリプト情報などを提供します。

# ベースURLの設定
# GitHub Pagesでサブディレクトリにデプロイする場合に必要です。
# 例: GitHub PagesのURLが 'https://username.github.io/my-project/' の場合、
# baseurl: "/my-project" と設定します。
# 今回のケースでは、/info-for-sora/first-step/Overview/ のパスに合わせて設定します。
baseurl: "/info-for-sora" # サイトのサブパス。もしルートにデプロイする場合は "" (空文字) にします。

# Jekyllのビルド設定 (通常はこのままでOK)
markdown: kramdown # Markdownパーサーとしてkramdownを使用
theme: null # 現在はMinimaテーマを使用しないためnullに設定
plugins:
  - jekyll-feed # RSSフィードを生成するプラグイン（現在は使用していませんが、残しておきます）

# Jekyllのビルドから除外するファイルやフォルダ
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CNAME
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/